### PR TITLE
Add new functions from 4.6.15 and 4.6.16

### PR DESCRIPTION
**Pull request by gp-rank13**
New functions for metronome and plugin parameter text.

### CODE REVIEW

**Comment by gp-rank13** [comment]
New functions have been tested and working as expected.

**Comment by sleiner** [comment]
Looks good to me 👍🏻 As far as I am concerned, we are only missing a formatter run and then we're good to go 🚀

**Review by sleiner — COMMENTED** [review]
Looks good to me 👍🏻 One formatter run and we're good to go 🚀

**Comment by sleiner** [comment]
@gp-rank13 do you want to take care of the formatting issues or should I?

**Review by sleiner — APPROVED** [review]

**Pull request merged**
