### PR TITLE
Changes GP 4621

### PR DESCRIPTION
**Pull request by gp-rank13**

### CODE REVIEW

**Comment by gp-rank13** [comment]
@sleiner I will need some 'clang-format for dummies' assistance in order to satisfy these checks. I also can't see what is exactly wrong with the format that's been highlighted.

**Comment by sleiner** [comment]
Hi @gp-rank13,

basically, there are only two things to keep in mind:
  1. Run clang-format
  2. Run the same version of the tool as CI does (see [`.github/workflows/format.yaml`](https://github.com/gigperformer/gp-sdk/blob/beta/.github/workflows/format.yaml#L15), currently it's v15)

I have my text editor configured to run clang-format on every save, so I never have to think about it :-)

> I also can't see what is exactly wrong with the format that's been highlighted.

If you run clang-format on it, that part of the code would change and that is an error by the definition of the job.
I did let the formatter run on my machine and it changes the lines like so:

```diff
diff --git a/c/include/gigperformer/sdk/imports.h b/c/include/gigperformer/sdk/imports.h
index 8cd7edb..6943186 100644
--- a/c/include/gigperformer/sdk/imports.h
+++ b/c/include/gigperformer/sdk/imports.h
@@ -53,10 +53,10 @@ extern "C"
     typedef int (*TGP_GetWidgetOutlineColor)(LibraryHandle h, const char *widgetName);
     typedef int (*TGP_GetWidgetOutlineThickness)(LibraryHandle h, const char *widgetName);
     typedef int (*TGP_GetWidgetOutlineRoundness)(LibraryHandle h, const char *widgetName);
-    typedef void (*TGP_SetWidgetBounds)(LibraryHandle h, const char *widgetName, int left, int top,
-                                         int width, int height);
-    typedef void (*TGP_GetWidgetBounds)(LibraryHandle h, const char *widgetName, int *left, int *top,
-                                         int *width, int *height);
+    typedef void (*TGP_SetWidgetBounds)(LibraryHandle h, const char *widgetName, int left, int top, int width,
+                                        int height);
+    typedef void (*TGP_GetWidgetBounds)(LibraryHandle h, const char *widgetName, int *left, int *top, int *width,
+                                        int *height);
 
     typedef int (*TGP_RGBAToColor)(LibraryHandle h, double red, double green, double blue, double alpha);
     typedef void (*TGP_ColorToRGBA)(LibraryHandle h, int color, double *red, double *green, double *blue,
```

**Comment by sleiner** [comment]
@gp-rank13 any objections against merging this?

**Comment by gp-rank13** [comment]
All ok from my end.

**Review by sleiner — APPROVED** [review]

**Pull request merged**
